<?php
/**
 * @file
 * The Organization module.
 */

/**
 * Implements hook_permission().
 */
function organization_permission() {
  $permissions = array();
  $permissions['organization: administer'] = array(
    'title' => t('Administer organizations'),
    'restrict access' => TRUE,
  );

  $permissions['organization: create'] = array(
    'title' => t('Create organizations'),
  );

  $actions = array('view' => 'View', 'update' => 'Edit', 'delete' => 'Delete');
  foreach (array('own', 'any') as $rel) {
    foreach ($actions as $op => $action) {
      $permissions["organization: $op $rel"] = array(
        'title' => t("$action $rel organizations"),
      );
    }
  }

  return $permissions;
}

/**
 * Implements hook_menu().
 */
function organization_menu() {
  $items = array();
  $items['user/%organization/delete'] = array(
    'title' => 'Delete',
    'access callback' => 'entity_access',
    'access arguments' => array('delete', 'user', 1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('organization_delete_form', 1),
    'file' => 'includes/organization.forms.inc',
    'type' => MENU_CALLBACK,
    'weight' => 2,
  );
  $items['user/%user/organizations/new'] = array(
    'title' => 'Create new organization',
    'access callback' => 'organization_access_create',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('organization_form', NULL, 1),
    'file' => 'includes/organization.forms.inc',
    'type' => MENU_LOCAL_ACTION,
    'weight' => 4,
  );
  $items['admin/config/people/organizations'] = array(
    'title' => 'Organizations',
    'description' => 'Administer organizations',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('organization: administer'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function organization_menu_alter(&$items) {
  $items['user/%user/edit']['access callback'] = 'organization_access_edit';

  foreach (organization_paths_to_block() as $path) {
    chain_menu_access_chain($items, $path, 'organization_access_block_orgs');
  }
}

/**
 * Find paths that should be restricted to users, not organizations.
 *
 * @return string[]
 *   A list of user/%user/* paths that should not be for organizations. Their
 *   second path argument (1) must be the user UID.
 */
function organization_paths_to_block() {
  $paths = array(
    'user/%user/shortcuts',
    'user/%user/cancel',
    'user/%/organizations',
  );
  drupal_alter(__FUNCTION__, $paths);

  return $paths;
}

/**
 * Access callback for blocking access to 'user' paths for organizations.
 *
 * @return bool
 *   TRUE if access is granted, FALSE otherwise.
 */
function organization_access_block_orgs() {
  $uid = arg(1);
  $account = is_numeric($uid) ? user_load($uid) : FALSE;

  return $account && $account->bundle != 'organization';
}

/**
 * Access callback for creating an organization.
 *
 * @return bool
 *   TRUE if access is granted, FALSE otherwise.
 */
function organization_access_create() {
  return user_access('organization: create') || user_access('organization: administer');
}

/**
 * Access callback for editing an organization.
 *
 * @return bool
 *   TRUE if access is granted, FALSE otherwise.
 */
function organization_access_edit($account) {
  return organization_user_entity_access('update', $account, NULL, 'user');
}

/**
 * URI callback for an organization.
 *
 * @param object $org
 *   The organization entity.
 *
 * @return array
 *   An array containing 'path'.
 */
function organization_uri($org) {
  return array('path' => 'user/' . $org->uid);
}

/**
 * Load callback for an organization.
 *
 * Intended as a menu load callback.
 *
 * @param int $uid
 *   The organization ID.
 *
 * @return object|FALSE
 *   An organization entity or FALSE if not found.
 */
function organization_load($uid) {
  $org = user_load($uid);
  if ($org && $org->bundle !== 'organization') {
    return FALSE;
  }

  return $org;
}

/**
 * Implements hook_entity_info_alter().
 *
 * @see organization_module_implements_alter()
 */
function organization_entity_info_alter(&$entity_info) {
  $entity_info['user']['entity keys']['bundle'] = 'bundle';
  if (!isset($entity_info['user']['bundles'])) {
    $entity_info['user']['bundles'] = array();
  }
  $entity_info['user']['bundles'] += array(
    'user' => array(
      'label' => t('User'),
    ),
    'organization' => array(
      'label' => t('Organization'),
      'uri callback' => 'organization_uri',
      'admin' => array(
        'path' => 'admin/config/people/organizations',
        'access arguments' => array('organization: administer'),
      ),
    ),
  );

  // Add a Teaser view mode.
  $entity_info['user']['view modes'] += array(
    'teaser' => array(
      'label' => t('Teaser'),
      'custom settings' => TRUE,
    ),
  );

  // Set an access callback for all user objects.
  $entity_info['user']['access callback'] = 'organization_user_entity_access';

  // Note: we cannot add a Views controller class for 'user' entities without
  // also adding an entity API controller class. The latter causes all sorts of
  // things to break. So we will handle Views the old-fashioned way, in
  // organization_views_data_alter().
}

/**
 * Implements hook_module_implements_alter().
 *
 * Moves the hook_entity_info_alter() implementation to the bottom so it is
 * invoked after the Entity API module.
 *
 * @see organization_entity_info_alter()
 */
function organization_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'entity_info_alter' || $hook === 'menu_alter') {
    $group = $implementations['organization'];
    unset($implementations['organization']);
    $implementations['organization'] = $group;
  }
}

/**
 * Generic entity access callback for users.
 *
 * Delegates to the default Entity API behavior for non-organizational users.
 */
function organization_user_entity_access($op, $entity = NULL, $account = NULL, $entity_type = NULL) {
  if ($entity_type !== 'user') {
    return FALSE;
  }
  if (!$entity || $entity->bundle !== 'organization') {
    return entity_metadata_user_access($op, $entity, $account);
  }
  if (user_access('organization: administer', $account)) {
    return TRUE;
  }
  if ($op == 'create') {
    return user_access('organization: create', $account);
  }
  if (user_access('organization: ' . $op . ' any', $account)) {
    return TRUE;
  }

  $account = $account ?: $GLOBALS['user'];
  $owner = organization_get_owner($entity);
  $own = $owner->uid == $account->uid;

  return $own && user_access('organization: ' . $op . ' own', $account);
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function organization_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Get the owner of an organization.
 *
 * @param object $org
 *   The organization entity.
 *
 * @return object
 *   The user account of the organization's owner.
 */
function organization_get_owner($org) {
  return entity_metadata_wrapper('user', $org)
    ->organization_owner
    ->value();
}

/**
 * Implements hook_user_presave().
 */
function organization_user_presave(&$edit, $account) {
  // Ensure the user account has a bundle set.
  if (!isset($account->bundle)) {
    $account->bundle = 'user';
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter the user registration and cancel form.
 */
function organization_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
    case 'user_profile_form':
    case 'organization_form':
      // Ensure the form contains a user 'bundle', so that validation works.
      $form += array(
        'bundle' => array(
          '#type' => 'value',
          '#value' => !empty($form_state['user']->bundle) ? $form_state['user']->bundle : 'user',
        ),
      );

      if ($form_state['user']->bundle === 'organization') {
        $form['#user_category'] = 'organization';
        unset(
          $form['account']['pass'],
          $form['account']['status'],
          $form['account']['roles'],
          $form['account']['notify'],
          $form['picture'],
          $form['signature_settings'],
          $form['actions']['cancel']
        );

        // Allow normal access to the 'name' field for organizations.
        unset($form['account']['name']['#access']);

        // Allow an empty e-mail address for organizations.
        $form['account']['mail']['#required'] = FALSE;
      }
      break;
  }
}

/**
 * Implements hook_field_access().
 */
function organization_field_access($op, $field, $entity_type, $entity, $account) {
  if ($entity_type === 'user') {
    switch ($field['field_name']) {
      // Ensure that normal users cannot change the organization owner.
      case 'organization_owner':
        return $op === 'view' || user_access('organization: administer', $account);
    }
  }
}

/**
 * Implements hook_user_view_alter().
 */
function organization_user_view_alter(&$build) {
  $account = $build['#account'];
  if ($account->bundle === 'organization') {
    // Remove the 'summary' (including 'History') from the organization page.
    unset($build['summary']);
  }
}

/**
 * Implements hook_user_login().
 *
 * Organizations should never be allowed to log in.
 */
function organization_user_login(&$edit, $account) {
  if ($account->bundle === 'organization') {
    watchdog('organization', 'Login attempt by organization @name (@id)', array(
      '@name' => $account->name,
      '@id' => $account->uid,
    ), WATCHDOG_ERROR);
    user_logout();
  }
}

/**
 * Implements hook_views_api().
 */
function organization_views_api() {
  return array('api' => 3);
}

/**
 * Implements hook_theme().
 */
function organization_theme() {
  return array(
    'organization' => array(
      'render element' => 'elements',
      'template' => 'organization',
      'file' => 'includes/organization.theme.inc',
    ),
  );
}

/**
 * Implements hook_entity_view_alter().
 */
function organization_entity_view_alter(&$build, $type) {
  if ($type === 'user' && isset($build['#bundle']) && $build['#bundle'] === 'organization') {
    $build['#theme'] = 'organization';
  }
}
